# -*- coding: utf-8 -*-

from easydict import EasyDict as edict

config = edict()

config.voc_v1 = edict({
    'workspace': './workspace/v1',
    'dataset': 'voc',
    'root_path': '/mnt/dataset/VOCdevkit',
    'train_sets': [(2012, 'train')],
    'val_sets': [(2012, 'val')],
    'test_sets': 'null',
    'num_classes': 21,
    'augment_ratio': 0.2,
    'rgb_std': (1,1,1),
    'rgb_means': (104,117,123),
    'model_name': 'RefineSSDMobileNet',
    'feature_maps': [40, 20, 10, 5],
    'shape': 320,
    'min_dim': 320,
    'steps': [8, 16, 32, 64],
    'min_sizes': [32, 64, 128, 256],
    'max_sizes': [],
    'aspect_ratios': [[2], [2], [2], [2]],
    'variance': [0.1, 0.2],
    'clip': True,
    'width_mult': 1.,
    'base_channel_num': 32,
    'use_refine': False,
    'batch_size': 2,
    'num_workers': 1,
    'base_lr': 2e-2,
    'momentum': 0.9,
    'weight_decay': 5e-4,
    'gamma': 0.1,
    'max_epoch': 201,
    'top_k': 200,
    'confidence_thresh': 0.15,
    'nms_thresh': 0.45,

    'enable_visdom': False,
    'prefix': 'coco-resnet-v1',
    'inteval': 10,
})

config.coco_v1 = edict({
    'workspace': './workspace/coco-v1',
    'dataset': 'coco',
    'root_path': '/mnt/dataset/coco',
    'train_sets' : 'train2017',
    'val_sets' : 'val2017',
    'test_sets': 'null',
    'num_classes': 81,
    'augment_ratio': 0.2,
    'rgb_std': (1,1,1),
    'rgb_means': (104,117,123),
    'model_name': 'RefineSSDMobileNet',
    'feature_maps': [40, 20, 10, 5],
    'shape': 320,
    'min_dim': 320,
    'steps': [8, 16, 32, 64],
    'min_sizes': [32, 64, 128, 256],
    'max_sizes': [],
    'aspect_ratios': [[2], [2], [2], [2]],
    'variance': [0.1, 0.2],
    'clip': True,
    'width_mult': 1.,
    'base_channel_num': 128,
    'use_refine': False,
    'batch_size': 8,
    'num_workers': 1,
    'base_lr': 2e-2,
    'momentum': 0.9,
    'weight_decay': 5e-4,
    'gamma': 0.1,
    'max_epoch': 201,
    'top_k': 200,
    'confidence_thresh': 0.15,
    'nms_thresh': 0.45,

    'enable_visdom': False,
    'prefix': 'coco-resnet-v1',
    'inteval': 10,
})


"""

config.list = {
    "v1" : {
        'feature_maps': [40, 20, 10, 5],
        'min_dim': 320,
        'steps': [8, 16, 32, 64],
        'min_sizes': [32, 64, 128, 256],
        'max_sizes': [],
        'aspect_ratios': [[2], [2], [2], [2]],
        'variance': [0.1, 0.2],
        'clip': True,
        'width_mult': 1,
        'base_channel_num': 128,
        'use_refine': True,
    },
    "v2" : {
        'model_name' : 'RefineSSDMobileNet',
        'train_sets' : 'person_train2017',
        'val_sets' : 'person_val2017',
        'num_classes' : 2,

        'feature_maps': [40, 20, 10, 5],
        'min_dim': 320,
        'steps': [8, 16, 32, 64],
        'min_sizes': [32, 64, 128, 256],
        'max_sizes': [],
        'aspect_ratios': [[2], [2], [2], [2]],
        'variance': [0.1, 0.2],
        'clip': True,

        'width_mult': 1.,
        'base_channel_num': 128,
        'use_refine': False,
        'batch_size': 64,
        'num_workers': 8,
        'shape': 320,
        'base_lr': 1e-3,
        'momentum': 0.9,
        'weight_decay': 5e-4,
        'gamma': 0.1,
        'max_epoch': 200,

        'top_k': 200,
        'confidence_thresh': 0.01,
        'nms_thresh': 0.45,
    },
    "v3" : {
        'root_path': '/mnt/dataset/coco',
        'model_name' : 'RefineSSDMobileNet',
        'train_sets' : 'person_train2017',
        'val_sets' : 'person_val2017',
        'num_classes' : 2,
        'augment_ratio': 0.2,
        'rgb_std': (1,1,1),
        'rgb_means': (104,117,123),

        'feature_maps': [40, 20, 10, 5],
        'min_dim': 320,
        'steps': [8, 16, 32, 64],
        'min_sizes': [32, 64, 128, 256],
        'max_sizes': [],
        'aspect_ratios': [[2], [2], [2], [2]],
        'variance': [0.1, 0.2],
        'clip': True,

        'width_mult': 0.75,
        'base_channel_num': 128,
        'use_refine': False,
        'batch_size': 48,
        'num_workers': 6,
        'shape': 320,
        'base_lr': 4e-2,
        'momentum': 0.9,
        'weight_decay': 5e-4,
        'gamma': 0.1,
        'max_epoch': 200,

        'top_k': 200,
        'confidence_thresh': 0.01,
        'nms_thresh': 0.45,
    },
    "v4" : {
        'root_path': '/mnt/dataset/coco',
        'model_name': 'RefineSSDMobileNetV1',
        'train_sets': 'person_train2017',
        'val_sets': 'person_val2017',
        'num_classes': 2,
        'augment_ratio': 0.2,
        'rgb_std': (1,1,1),
        'rgb_means': (104,117,123),

        'feature_maps': [40, 20, 10, 5],
        'shape': 320,
        'min_dim': 320,
        'steps': [8, 16, 32, 64],
        'min_sizes': [32, 64, 128, 256],
        'max_sizes': [],
        'aspect_ratios': [[2], [2], [2], [2]],
        'variance': [0.1, 0.2],
        'clip': True,

        'width_mult': 1,
        'base_channel_num': 128,
        'use_refine': True,
        'batch_size': 128,
        'num_workers': 8,
        'shape': 320,
        'base_lr': 5e-3,
        'momentum': 0.9,
        'weight_decay': 4e-4,
        'gamma': 0.1,
        'max_epoch': 201,

        'top_k': 200,
        'confidence_thresh': 0.01,
        'nms_thresh': 0.45,
    },
    "v5" : {
        'root_path': '/mnt/dataset/coco',
        'train_sets' : 'person_train2017',
        'val_sets' : 'person_val2017',
        'num_classes' : 2,
        'augment_ratio': 0.2,
        'rgb_std': (1,1,1),
        'rgb_means': (104,117,123),

        'model_name' : 'RefineSSDMobileNet',
        'feature_maps': [40, 20, 10, 5],
        'min_dim': 320,
        'steps': [8, 16, 32, 64],
        'min_sizes': [32, 64, 128, 256],
        'max_sizes': [],
        'aspect_ratios': [[2], [2], [2], [2]],
        # 'aspect_ratios': [[2, 3], [2], [2], [2]],
        'variance': [0.1, 0.2],
        'clip': True,

        'width_mult': 0.5,
        'base_channel_num': 128,
        'use_refine': True,
        # 'batch_size': 256,
        # 'num_workers': 64,
        'batch_size': 4,
        'num_workers': 2,
        'shape': 320,
        'base_lr': 8e-2,
        'momentum': 0.9,
        'weight_decay': 5e-4,
        'gamma': 0.1,
        'max_epoch': 201,

        'top_k': 100,
        'confidence_thresh': 0.15,
        # 'top_k': 200,
        # 'confidence_thresh': 0.01,
        'nms_thresh': 0.45,
    },
    "v6" : {
        'model_name' : 'RefineSSDMobileNet',
        'train_sets' : 'train2017',
        'val_sets' : 'val2017',
        'num_classes' : 81,

        'feature_maps': [40, 20, 10, 5],
        'min_dim': 320,
        'steps': [8, 16, 32, 64],
        'min_sizes': [32, 64, 128, 256],
        'max_sizes': [],
        'aspect_ratios': [[2], [2], [2], [2]],
        # 'aspect_ratios': [[2, 3], [2], [2], [2]],
        'variance': [0.1, 0.2],
        'clip': True,

        'width_mult': 1.,
        'base_channel_num': 256,
        'use_refine': True,
        'batch_size': 96,
        'num_workers': 32,
        'shape': 320,
        'base_lr': 4e-2,
        'momentum': 0.9,
        'weight_decay': 5e-4,
        'gamma': 0.1,
        'max_epoch': 201,

        # 'top_k': 100,
        # 'confidence_thresh': 0.15,
        'top_k': 200,
        'confidence_thresh': 0.01,
        'nms_thresh': 0.45,
    },

    # resnet config
    "r1" : {
        'model_name' : 'RefineSSDSEResNeXt',
        'train_sets' : 'person_train2017',
        'val_sets' : 'person_val2017',
        'num_classes' : 2,
        'augment_ratio': 0.2,
        'rgb_std': (1,1,1),
        'rgb_means': (104,117,123),

        'feature_maps': [40, 20, 10, 5],
        'min_dim': 320,
        'steps': [8, 16, 32, 64],
        'min_sizes': [32, 64, 128, 256],
        'max_sizes': [],
        'aspect_ratios': [[3], [3], [3], [3]],
        'variance': [0.1, 0.2],
        'clip': True,

        'width_mult': 1.,
        'base_channel_num': 256,
        'use_refine': True,
        'batch_size': 128,
        'num_workers': 8,
        'shape': 320,
        'base_lr': 5e-2,
        'momentum': 0.9,
        'weight_decay': 5e-4,
        'gamma': 0.1,
        'max_epoch': 201,

        'top_k': 200,
        'confidence_thresh': 0.15,
        # 'top_k': 200,
        # 'confidence_thresh': 0.01,
        'nms_thresh': 0.45,
    },

    # coco image set
    "coco-v1" : {
        'model_name' : 'RefineSSDSEResNeXt',
        'root_path': '/mnt/dataset/coco',
        'train_sets' : 'train2017',
        'val_sets' : 'val2017',
        'num_classes' : 81,
        'augment_ratio': 0.2,
        'rgb_std': (1,1,1),
        'rgb_means': (0,0,0),

        'feature_maps': [40, 20, 10, 5],
        'min_dim': 320,
        'steps': [8, 16, 32, 64],
        'min_sizes': [32, 64, 128, 256],
        'max_sizes': [],
        'aspect_ratios': [[3], [3], [3], [3]],
        'variance': [0.1, 0.2],
        'clip': True,

        'width_mult': 1.,
        'base_channel_num': 256,
        'use_refine': True,
        'batch_size': 32,
        'num_workers': 1,
        'shape': 320,
        'base_lr': 1e-2,
        'momentum': 0.9,
        'weight_decay': 5e-4,
        'gamma': 0.1,
        'max_epoch': 201,

        'top_k': 200,
        'confidence_thresh': 0.15,
        'nms_thresh': 0.45,
    },

    "coco-v2" : {
        'model_name' : 'RefineSSDSEResNeXt',
        'root_path': '/mnt/dataset/coco',
        'train_sets' : 'train2017',
        'val_sets' : 'val2017',
        'num_classes' : 81,
        'augment_ratio': 0.2,
        'rgb_std': (1,1,1),
        'rgb_means': (0,0,0),

        'feature_maps': [40, 20, 10, 5],
        'min_dim': 320,
        'steps': [8, 16, 32, 64],
        'min_sizes': [32, 64, 128, 256],
        'max_sizes': [],
        'aspect_ratios': [[3], [3], [3], [3]],
        'variance': [0.1, 0.2],
        'clip': True,

        'width_mult': 1.,
        'base_channel_num': 256,
        'use_refine': False,
        'batch_size': 32,
        'num_workers': 1,
        'shape': 320,
        'base_lr': 1e-2,
        'momentum': 0.9,
        'weight_decay': 5e-4,
        'gamma': 0.1,
        'max_epoch': 201,

        'top_k': 200,
        'confidence_thresh': 0.15,
        'nms_thresh': 0.45,
    },


    # resnet config
    "c1" : {
        'root_path': '/mnt/dataset/car',
        'train_sets': 'train_a',
        'val_sets': 'train_b',
        'test_sets': 'test_a',
        'num_classes': 2,
        'augment_ratio': 0.2,
        'rgb_std': (1,1,1),
        'rgb_means': (104,117,123),

        'model_name': 'RefineSSDSEResNeXt',
        'feature_maps': [40, 20, 10, 5],
        'shape': 320,
        'min_dim': 320,
        'steps': [8, 16, 32, 64],
        'min_sizes': [32, 64, 128, 256],
        'max_sizes': [],
        'aspect_ratios': [[2], [2], [2], [2]],
        'variance': [0.1, 0.2],
        'clip': True,

        'width_mult': 1.,
        'base_channel_num': 256,
        'use_refine': True,
        'batch_size': 96,
        'num_workers': 4,
        'base_lr': 3e-2,
        'momentum': 0.9,
        'weight_decay': 5e-4,
        'gamma': 0.1,
        'max_epoch': 201,

        'top_k': 200,
        'confidence_thresh': 0.15,
        'nms_thresh': 0.45,
    },

    "v-test" : {
        # 'shape': [320, 320], # [width, height]
        # 'feature_maps': [[40, 40], [20, 20], [10, 10], [5, 5]],
        # 'steps': [[8, 8], [16, 16], [32, 32], [64, 64]],
        # 'aspect_ratios': [[2], [2], [2], [2]],
        # 'min_sizes': [[32, 32], [64, 64], [128, 128], [256, 256]],

        'feature_maps': [[64, 36], [32, 18], [16, 9], [8, 5]],
        'shape': [512, 288], # [width, height]
        'steps': [[8, 8], [16, 16], [32, 32], [64, 56]],
        'aspect_ratios': [[2, 3], [2, 3], [2, 3], [2, 3]],
        'min_sizes': [[32, 24], [64, 48], [128, 96], [256, 196]],
        'max_sizes': [],
        'variance': [0.1, 0.2],
        'clip': True,

        'width_mult': 0.75,
        'base_channel_num': 128,
        'use_refine': True,
        'batch_size': 192,
        'num_workers': 36,
        'base_lr': 4e-2,
        'momentum': 0.9,
        'weight_decay': 5e-4,
        'gamma': 0.1,
        'max_epoch': 200,

        'top_k': 200,
        'confidence_thresh': 0.01,
        'nms_thresh': 0.45,
    },
}

"""


